# Generated by Django 5.2 on 2025-04-24 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Program Category',
                'verbose_name_plural': 'Program Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('eligibility_criteria', models.TextField(blank=True, verbose_name='Eligibility Criteria')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of clients', null=True, verbose_name='Capacity')),
                ('location', models.CharField(help_text='Where the program is being conducted', max_length=255, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='health_programs.programcategory', verbose_name='Category')),
            ],
        ),
    ]
